# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aziz Ali
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website and blog of Aziz Ali, a Pakistani entrepreneur and founder of iLoveCoding.org. 
  Here I share my life experiences, lessons learned in business, relationship, spirituality, and more.
  I also openly share the tools I used in my projects, and the people and books that inspire me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://azizali.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: heyaziz
github_username:  azizali

permalink: /:title/

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

sass:
  load_paths:
    - _sass
    - node_modules

google_analytics: UA-16845265-7

disqus:
  shortname: azizali

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

paginate: 10
paginate_path: "/blog/page:num/"