---
title: Aziz Ali
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: This is the personal website and blog of Aziz Ali, a Pakistani entrepreneur
  and founder of iLoveCoding.org.  Here I share my life experiences, lessons learned
  in business, relationship, spirituality, and more. I also openly share the tools
  I used in my projects, and the people and books that inspire me.
baseurl: ''
url: https://azizali.com
twitter_username: heyaziz
github_username: azizali
permalink: "/:title/"
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-paginate
- jemoji
sass:
  load_paths:
  - _sass
  - node_modules
google_analytics: UA-16845265-7
disqus:
  shortname: azizali
exclude:
- Gemfile
- Gemfile.lock
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
paginate: 10
paginate_path: "/blog/page:num/"
